import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Suleyman",
      email: "admin@mail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Ahmet",
      email: "user@mail.com",
      password: bcrypt.hashSync("12345", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "Nike T-Shirt",
      category: "Shirts",
      image: "/images/p1.jpeg",
      countInStock: 10,
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product.",
    },
    {
      _id: "2",
      name: "Reading Book",
      category: "Books",
      image: "/images/p2.jpeg",
      countInStock: 7,
      price: 6,
      brand: "Booker",
      rating: 4.0,
      numReviews: 2,
      description: "High quality product.",
    },
    {
      _id: "3",
      name: "Nike Shoes",
      category: "Shoes",
      image: "/images/p3.jpeg",
      countInStock: 2,
      price: 200,
      brand: "Nike",
      rating: 5.0,
      numReviews: 73,
      description: "High quality product.",
    },
    {
      _id: "4",
      name: "Red Bike",
      category: "Bikes",
      image: "/images/p4.jpeg",
      countInStock: 0,
      price: 400,
      brand: "Redisht",
      rating: 1.6,
      numReviews: 2,
      description: "Low-quality product.",
    },
    {
      _id: "5",
      name: "Blue Car",
      category: "Cars",
      image: "/images/p5.jpeg",
      countInStock: 1,
      price: 20000,
      brand: "Renault",
      rating: 4.5,
      numReviews: 174,
      description: "High quality product.",
    },
    {
      _id: "6",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p6.jpeg",
      countInStock: 9,
      price: 50,
      brand: "Nike",
      rating: 4.5,
      numReviews: 24,
      description: "High quality product.",
    },
  ],
};

export default data;
